// data/depots.js
import mongoose from "mongoose";

// This is your "key ring". It maps a simple name to a unique ObjectId.
// We EXPORT this so other files can use it.
export const depotIds = {
  vijayawada: new mongoose.Types.ObjectId(),
  guntur: new mongoose.Types.ObjectId(),
  tenali: new mongoose.Types.ObjectId(),
  ongole: new mongoose.Types.ObjectId(),
  nellore: new mongoose.Types.ObjectId(),
  tirupati: new mongoose.Types.ObjectId(),
  chittoor: new mongoose.Types.ObjectId(),
  kadapa: new mongoose.Types.ObjectId(),
  anantapur: new mongoose.Types.ObjectId(),
  kurnool: new mongoose.Types.ObjectId(),
  visakhapatnam: new mongoose.Types.ObjectId(),
  vizianagaram: new mongoose.Types.ObjectId(),
  srikakulam: new mongoose.Types.ObjectId(),
  rajahmundry: new mongoose.Types.ObjectId(),
  kakinada: new mongoose.Types.ObjectId(),
  bhimavaram: new mongoose.Types.ObjectId(),
  machilipatnam: new mongoose.Types.ObjectId(),
  gudivada: new mongoose.Types.ObjectId(),
  amalapuram: new mongoose.Types.ObjectId(),
  narasapuram: new mongoose.Types.ObjectId(),
  proddatur: new mongoose.Types.ObjectId(),
  madanapalle: new mongoose.Types.ObjectId(),
  hindupur: new mongoose.Types.ObjectId(),
  nandyal: new mongoose.Types.ObjectId(),
  parvathipuram: new mongoose.Types.ObjectId(),
  hyderabadMgbs: new mongoose.Types.ObjectId(),
  secunderabadJbs: new mongoose.Types.ObjectId(),
  warangal: new mongoose.Types.ObjectId(),
  hanamkonda: new mongoose.Types.ObjectId(),
  khammam: new mongoose.Types.ObjectId(),
  karimnagar: new mongoose.Types.ObjectId(),
  nizamabad: new mongoose.Types.ObjectId(),
  adilabad: new mongoose.Types.ObjectId(),
  mancherial: new mongoose.Types.ObjectId(),
  mahbubnagar: new mongoose.Types.ObjectId(),
  nalgonda: new mongoose.Types.ObjectId(),
  suryapet: new mongoose.Types.ObjectId(),
  kodad: new mongoose.Types.ObjectId(),
  siddipet: new mongoose.Types.ObjectId(),
  medak: new mongoose.Types.ObjectId(),
  zaheerabad: new mongoose.Types.ObjectId(),
  bhongir: new mongoose.Types.ObjectId(),
  jangaon: new mongoose.Types.ObjectId(),
  miryalaguda: new mongoose.Types.ObjectId(),
  kamareddy: new mongoose.Types.ObjectId(),
  bhadrachalam: new mongoose.Types.ObjectId(),
  palvoncha: new mongoose.Types.ObjectId(),
  kothagudem: new mongoose.Types.ObjectId(),
  manuguru: new mongoose.Types.ObjectId(),
  siricilla: new mongoose.Types.ObjectId(),
};

export const depots = [
  {
    _id: depotIds.vijayawada,
    name: "Vijayawada Depot",
    city: "Vijayawada",
    location: { type: "Point", coordinates: [80.648, 16.5062] },
  },
  {
    _id: depotIds.guntur,
    name: "Guntur Depot",
    city: "Guntur",
    location: { type: "Point", coordinates: [80.435, 16.3142] },
  },
  {
    _id: depotIds.tenali,
    name: "Tenali Depot",
    city: "Tenali",
    location: { type: "Point", coordinates: [80.6406, 16.2417] },
  },
  {
    _id: depotIds.ongole,
    name: "Ongole Depot",
    city: "Ongole",
    location: { type: "Point", coordinates: [80.0499, 15.5057] },
  },
  {
    _id: depotIds.nellore,
    name: "Nellore Depot",
    city: "Nellore",
    location: { type: "Point", coordinates: [79.9865, 14.4426] },
  },
  {
    _id: depotIds.tirupati,
    name: "Tirupati Depot",
    city: "Tirupati",
    location: { type: "Point", coordinates: [79.4192, 13.6288] },
  },
  {
    _id: depotIds.chittoor,
    name: "Chittoor Depot",
    city: "Chittoor",
    location: { type: "Point", coordinates: [79.1003, 13.2172] },
  },
  {
    _id: depotIds.kadapa,
    name: "Kadapa Depot",
    city: "Kadapa",
    location: { type: "Point", coordinates: [78.8296, 14.4673] },
  },
  {
    _id: depotIds.anantapur,
    name: "Anantapur Depot",
    city: "Anantapur",
    location: { type: "Point", coordinates: [77.605, 14.6819] },
  },
  {
    _id: depotIds.kurnool,
    name: "Kurnool Depot",
    city: "Kurnool",
    location: { type: "Point", coordinates: [78.04, 15.8281] },
  },
  {
    _id: depotIds.visakhapatnam,
    name: "Visakhapatnam Depot",
    city: "Visakhapatnam",
    location: { type: "Point", coordinates: [83.2185, 17.6868] },
  },
  {
    _id: depotIds.vizianagaram,
    name: "Vizianagaram Depot",
    city: "Vizianagaram",
    location: { type: "Point", coordinates: [83.3966, 18.113] },
  },
  {
    _id: depotIds.srikakulam,
    name: "Srikakulam Depot",
    city: "Srikakulam",
    location: { type: "Point", coordinates: [83.8973, 18.2969] },
  },
  {
    _id: depotIds.rajahmundry,
    name: "Rajahmundry Depot",
    city: "Rajahmundry",
    location: { type: "Point", coordinates: [81.804, 17.0005] },
  },
  {
    _id: depotIds.kakinada,
    name: "Kakinada Depot",
    city: "Kakinada",
    location: { type: "Point", coordinates: [82.2475, 16.9891] },
  },
  {
    _id: depotIds.bhimavaram,
    name: "Bhimavaram Depot",
    city: "Bhimavaram",
    location: { type: "Point", coordinates: [81.5212, 16.5449] },
  },
  {
    _id: depotIds.machilipatnam,
    name: "Machilipatnam Depot",
    city: "Machilipatnam",
    location: { type: "Point", coordinates: [81.1389, 16.1875] },
  },
  {
    _id: depotIds.gudivada,
    name: "Gudivada Depot",
    city: "Gudivada",
    location: { type: "Point", coordinates: [80.9928, 16.441] },
  },
  {
    _id: depotIds.amalapuram,
    name: "Amalapuram Depot",
    city: "Amalapuram",
    location: { type: "Point", coordinates: [82.0061, 16.579] },
  },
  {
    _id: depotIds.narasapuram,
    name: "Narasapuram Depot",
    city: "Narasapuram",
    location: { type: "Point", coordinates: [81.6995, 16.433] },
  },
  {
    _id: depotIds.proddatur,
    name: "Proddatur Depot",
    city: "Proddatur",
    location: { type: "Point", coordinates: [78.5631, 14.7502] },
  },
  {
    _id: depotIds.madanapalle,
    name: "Madanapalle Depot",
    city: "Madanapalle",
    location: { type: "Point", coordinates: [78.501, 13.5503] },
  },
  {
    _id: depotIds.hindupur,
    name: "Hindupur Depot",
    city: "Hindupur",
    location: { type: "Point", coordinates: [77.4914, 13.8289] },
  },
  {
    _id: depotIds.nandyal,
    name: "Nandyal Depot",
    city: "Nandyal",
    location: { type: "Point", coordinates: [78.4829, 15.4786] },
  },
  {
    _id: depotIds.parvathipuram,
    name: "Parvathipuram Depot",
    city: "Parvathipuram",
    location: { type: "Point", coordinates: [83.4281, 18.783] },
  },

  // --- Telangana Depots ---
  {
    _id: depotIds.hyderabadMgbs,
    name: "Hyderabad MGBS Depot",
    city: "Hyderabad",
    location: { type: "Point", coordinates: [78.4867, 17.385] },
  },
  {
    _id: depotIds.secunderabadJbs,
    name: "Secunderabad Jubilee Bus Station Depot",
    city: "Secunderabad",
    location: { type: "Point", coordinates: [78.5245, 17.4399] },
  },
  {
    _id: depotIds.warangal,
    name: "Warangal Depot",
    city: "Warangal",
    location: { type: "Point", coordinates: [79.5941, 17.9784] },
  },
  {
    _id: depotIds.hanamkonda,
    name: "Hanamkonda Depot",
    city: "Hanamkonda",
    location: { type: "Point", coordinates: [79.5583, 17.9939] },
  },
  {
    _id: depotIds.khammam,
    name: "Khammam Depot",
    city: "Khammam",
    location: { type: "Point", coordinates: [80.1406, 17.2473] },
  },
  {
    _id: depotIds.karimnagar,
    name: "Karimnagar Depot",
    city: "Karimnagar",
    location: { type: "Point", coordinates: [79.1288, 18.4386] },
  },
  {
    _id: depotIds.nizamabad,
    name: "Nizamabad Depot",
    city: "Nizamabad",
    location: { type: "Point", coordinates: [78.0941, 18.6725] },
  },
  {
    _id: depotIds.adilabad,
    name: "Adilabad Depot",
    city: "Adilabad",
    location: { type: "Point", coordinates: [78.5359, 19.6641] },
  },
  {
    _id: depotIds.mancherial,
    name: "Mancherial Depot",
    city: "Mancherial",
    location: { type: "Point", coordinates: [79.4635, 18.8707] },
  },
  {
    _id: depotIds.mahbubnagar,
    name: "Mahbubnagar Depot",
    city: "Mahbubnagar",
    location: { type: "Point", coordinates: [77.985, 16.748] },
  },
  {
    _id: depotIds.nalgonda,
    name: "Nalgonda Depot",
    city: "Nalgonda",
    location: { type: "Point", coordinates: [79.2674, 17.0575] },
  },
  {
    _id: depotIds.suryapet,
    name: "Suryapet Depot",
    city: "Suryapet",
    location: { type: "Point", coordinates: [79.6205, 17.1405] },
  },
  {
    _id: depotIds.kodad,
    name: "Kodad Depot",
    city: "Kodad",
    location: { type: "Point", coordinates: [79.9656, 16.9985] },
  },
  {
    _id: depotIds.siddipet,
    name: "Siddipet Depot",
    city: "Siddipet",
    location: { type: "Point", coordinates: [78.8521, 18.1048] },
  },
  {
    _id: depotIds.medak,
    name: "Medak Depot",
    city: "Medak",
    location: { type: "Point", coordinates: [78.26, 18.045] },
  },
  {
    _id: depotIds.zaheerabad,
    name: "Zaheerabad Depot",
    city: "Zaheerabad",
    location: { type: "Point", coordinates: [77.55, 17.6833] },
  },
  {
    _id: depotIds.bhongir,
    name: "Bhongir Depot",
    city: "Bhongir",
    location: { type: "Point", coordinates: [78.883, 17.515] },
  },
  {
    _id: depotIds.jangaon,
    name: "Jangaon Depot",
    city: "Jangaon",
    location: { type: "Point", coordinates: [79.1516, 17.726] },
  },
  {
    _id: depotIds.miryalaguda,
    name: "Miryalaguda Depot",
    city: "Miryalaguda",
    location: { type: "Point", coordinates: [79.5655, 16.873] },
  },
  {
    _id: depotIds.kamareddy,
    name: "Kamareddy Depot",
    city: "Kamareddy",
    location: { type: "Point", coordinates: [78.344, 18.3166] },
  },
  {
    _id: depotIds.bhadrachalam,
    name: "Bhadrachalam Depot",
    city: "Bhadrachalam",
    location: { type: "Point", coordinates: [80.8893, 17.6686] },
  },
  {
    _id: depotIds.palvoncha,
    name: "Palvoncha Depot",
    city: "Palvoncha",
    location: { type: "Point", coordinates: [80.684, 17.601] },
  },
  {
    _id: depotIds.kothagudem,
    name: "Kothagudem Depot",
    city: "Kothagudem",
    location: { type: "Point", coordinates: [80.639, 17.5511] },
  },
  {
    _id: depotIds.manuguru,
    name: "Manuguru Depot",
    city: "Manuguru",
    location: { type: "Point", coordinates: [80.826, 17.8974] },
  },
  {
    _id: depotIds.siricilla,
    name: "Siricilla Depot",
    city: "Siricilla",
    location: { type: "Point", coordinates: [78.8092, 18.3886] },
  },
];

// Vehicles
const vehicles = [
  {
    _id: "veh1",
    bus_number: "AP16AB2001",
    service_type: "Ultra Deluxe",
    total_seats: 45,
    amenities: ["AC", "WiFi"],
    depot_id: "dep1",
    status: "ON_TRIP",
  },
  {
    _id: "veh2",
    bus_number: "AP16AB2002",
    service_type: "Express",
    total_seats: 40,
    amenities: ["AC"],
    depot_id: "dep2",
    status: "ON_TRIP",
  },
  {
    _id: "veh3",
    bus_number: "AP16AB2003",
    service_type: "Super Luxury",
    total_seats: 48,
    amenities: ["WiFi", "Charging Ports"],
    depot_id: "dep3",
    status: "ON_TRIP",
  },
  {
    _id: "veh4",
    bus_number: "AP16AB2004",
    service_type: "Sleeper",
    total_seats: 36,
    amenities: ["Blankets", "Pillows"],
    depot_id: "dep4",
    status: "ON_TRIP",
  },
];

// Routes
const routes = [
  {
    _id: "route1",
    routeName: "Vijayawada → Tirupati",
    origin: "Vijayawada Depot",
    destination: "Tirupati Depot",
    distance_km: 260,
    stops: [
      {
        name: "Vijayawada Depot",
        latitude: 16.5062,
        longitude: 80.648,
        arrival_offset_mins: 0,
        departure_offset_mins: 5,
      },
      {
        name: "Guntur Depot",
        latitude: 16.3142,
        longitude: 80.435,
        arrival_offset_mins: 45,
        departure_offset_mins: 50,
      },
      {
        name: "Nellore Depot",
        latitude: 14.4426,
        longitude: 79.9865,
        arrival_offset_mins: 180,
        departure_offset_mins: 185,
      },
      {
        name: "Tirupati Depot",
        latitude: 13.6288,
        longitude: 79.4192,
        arrival_offset_mins: 300,
        departure_offset_mins: 305,
      },
    ],
  },
  {
    _id: "route2",
    routeName: "Hyderabad → Suryapet",
    origin: "Hyderabad Depot",
    destination: "Suryapet Depot",
    distance_km: 130,
    stops: [
      {
        name: "Hyderabad MGBS Depot",
        latitude: 17.385,
        longitude: 78.4867,
        arrival_offset_mins: 0,
        departure_offset_mins: 5,
      },
      {
        name: "Kodad Depot",
        latitude: 16.9985,
        longitude: 79.9656,
        arrival_offset_mins: 90,
        departure_offset_mins: 95,
      },
      {
        name: "Suryapet Depot",
        latitude: 17.1405,
        longitude: 79.6205,
        arrival_offset_mins: 120,
        departure_offset_mins: 125,
      },
    ],
  },
  {
    _id: "route3",
    routeName: "Vizag → Rajahmundry",
    origin: "Visakhapatnam Depot",
    destination: "Rajahmundry Depot",
    distance_km: 200,
    stops: [
      {
        name: "Visakhapatnam Depot",
        latitude: 17.6868,
        longitude: 83.2185,
        arrival_offset_mins: 0,
        departure_offset_mins: 5,
      },
      {
        name: "Vizianagaram Depot",
        latitude: 18.113,
        longitude: 83.3966,
        arrival_offset_mins: 60,
        departure_offset_mins: 65,
      },
      {
        name: "Rajahmundry Depot",
        latitude: 17.0005,
        longitude: 81.804,
        arrival_offset_mins: 180,
        departure_offset_mins: 185,
      },
    ],
  },
  {
    _id: "route4",
    routeName: "Kurnool → Anantapur",
    origin: "Kurnool Depot",
    destination: "Anantapur Depot",
    distance_km: 210,
    stops: [
      {
        name: "Kurnool Depot",
        latitude: 15.8281,
        longitude: 78.0373,
        arrival_offset_mins: 0,
        departure_offset_mins: 5,
      },
      {
        name: "Dhone Depot",
        latitude: 15.395,
        longitude: 77.875,
        arrival_offset_mins: 60,
        departure_offset_mins: 65,
      },
      {
        name: "Anantapur Depot",
        latitude: 14.6819,
        longitude: 77.6006,
        arrival_offset_mins: 150,
        departure_offset_mins: 155,
      },
    ],
  },
];

// Trips (Realtime positions)
const trips = [
  {
    _id: "trip1",
    route_id: "route1",
    vehicle_id: "veh1",
    driver_id: "driver1",
    conductor_id: "conductor1",
    departure_datetime: new Date("2025-09-16T08:00:00Z"),
    arrival_datetime: new Date("2025-09-16T13:00:00Z"),
    status: "IN_TRANSIT",
    current_passenger_count: 32,
    last_location_update: new Date("2025-09-16T10:30:00Z"),
    live_location: { latitude: 15.5, longitude: 80.3 },
    visited_stops: [
      {
        stop_name: "Vijayawada Depot",
        actual_arrival_time: new Date("2025-09-16T08:00:00Z"),
        actual_departure_time: new Date("2025-09-16T08:05:00Z"),
      },
      {
        stop_name: "Guntur Depot",
        actual_arrival_time: new Date("2025-09-16T09:45:00Z"),
        actual_departure_time: new Date("2025-09-16T09:50:00Z"),
      },
    ],
  },
  {
    _id: "trip2",
    route_id: "route2",
    vehicle_id: "veh2",
    driver_id: "driver2",
    conductor_id: "conductor2",
    departure_datetime: new Date("2025-09-16T09:00:00Z"),
    arrival_datetime: new Date("2025-09-16T11:30:00Z"),
    status: "IN_TRANSIT",
    current_passenger_count: 28,
    last_location_update: new Date("2025-09-16T10:00:00Z"),
    live_location: { latitude: 17.2, longitude: 79.8 },
    visited_stops: [
      {
        stop_name: "Hyderabad MGBS Depot",
        actual_arrival_time: new Date("2025-09-16T09:00:00Z"),
        actual_departure_time: new Date("2025-09-16T09:05:00Z"),
      },
    ],
  },
  {
    _id: "trip3",
    route_id: "route3",
    vehicle_id: "veh3",
    driver_id: "driver3",
    conductor_id: "conductor3",
    departure_datetime: new Date("2025-09-16T07:00:00Z"),
    arrival_datetime: new Date("2025-09-16T12:00:00Z"),
    status: "IN_TRANSIT",
    current_passenger_count: 40,
    last_location_update: new Date("2025-09-16T09:30:00Z"),
    live_location: { latitude: 17.9, longitude: 82.5 },
    visited_stops: [
      {
        stop_name: "Visakhapatnam Depot",
        actual_arrival_time: new Date("2025-09-16T07:00:00Z"),
        actual_departure_time: new Date("2025-09-16T07:05:00Z"),
      },
    ],
  },
  {
    _id: "trip4",
    route_id: "route4",
    vehicle_id: "veh4",
    driver_id: "driver4",
    conductor_id: "conductor4",
    departure_datetime: new Date("2025-09-16T06:30:00Z"),
    arrival_datetime: new Date("2025-09-16T10:00:00Z"),
    status: "IN_TRANSIT",
    current_passenger_count: 35,
    last_location_update: new Date("2025-09-16T08:45:00Z"),
    live_location: { latitude: 15.1, longitude: 77.75 },
    visited_stops: [
      {
        stop_name: "Kurnool Depot",
        actual_arrival_time: new Date("2025-09-16T06:30:00Z"),
        actual_departure_time: new Date("2025-09-16T06:35:00Z"),
      },
    ],
  },
];
