export const busesData = {
  depot_name: "Bhimavaram APSRTC Depot",
  data_generated_on: "2025-09-16",
  bus_services: [
    {
      route_id: "BVRM-VJA-101",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Vijayawada",
      bus_numbers: ["111", "111H", "112"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 180,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 04:55 to 20:20",
      },
    },
    {
      route_id: "BVRM-VJA-102",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Vijayawada",
      bus_numbers: ["999A"],
      service_type: "Indra (AC)",
      total_seats: 40,
      amenities: ["AC", "Recliner Seats", "Charging Ports"],
      estimated_duration_mins: 160,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-HYD-201",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Hyderabad (MGBS)",
      bus_numbers: ["7745"],
      service_type: "Garuda (AC Volvo)",
      total_seats: 45,
      amenities: ["AC", "Recliner Seats", "Charging Ports", "Water Bottle"],
      estimated_duration_mins: 510,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["19:30", "20:30", "21:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-HYD-202",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Hyderabad (BHEL)",
      bus_numbers: ["7781"],
      service_type: "Super Luxury (Non-AC)",
      total_seats: 40,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 540,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["19:00", "20:00", "21:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKP-301",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Visakhapatnam",
      bus_numbers: ["444V"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 420,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:30", "08:30", "13:45", "21:00", "22:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-RJY-401",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Rajahmundry",
      bus_numbers: ["193", "233A"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 150,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 40 minutes from 04:50 to 19:35",
      },
    },
    {
      route_id: "BVRM-ELR-501",
      platform_number: 2,
      origin_depot: "Bhimavaram",
      destination: "Eluru",
      bus_numbers: ["7A"],
      service_type: "Express",
      total_seats: 55,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 100,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 05:35 to 21:15",
      },
    },
    {
      route_id: "BVRM-TPG-601",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tadepalligudem",
      bus_numbers: ["201T"],
      service_type: "Express",
      total_seats: 55,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 05:00 to 21:00",
      },
    },
    {
      route_id: "BVRM-TNK-701",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tanuku",
      bus_numbers: ["252"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 25 minutes from 05:10 to 20:40",
      },
    },
    {
      route_id: "BVRM-NSP-801",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Narasapuram",
      bus_numbers: ["116"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 05:30 to 20:30",
      },
    },
    {
      route_id: "BVRM-PLK-901",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Palakollu",
      bus_numbers: ["158"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 45,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 25 minutes from 05:00 to 21:25",
      },
    },
    {
      route_id: "BVRM-AKVD-1001",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Akividu",
      bus_numbers: ["301"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 40,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 06:00 to 21:00",
      },
    },
    {
      route_id: "BVRM-KKLR-1101",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Kaikalur",
      bus_numbers: ["311"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 70,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:15",
          "07:45",
          "09:15",
          "11:30",
          "14:00",
          "16:30",
          "18:45",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-UNDI-1201",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Undi",
      bus_numbers: ["303"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 30,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 45 minutes from 06:30 to 20:00",
      },
    },
    {
      route_id: "BVRM-KKD-1301",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Kakinada",
      bus_numbers: ["555K"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 240,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:00", "07:15", "09:30", "11:45", "14:00", "16:15"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GNT-1401",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Guntur",
      bus_numbers: ["888G"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 210,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["06:45", "09:00", "11:15", "15:00", "17:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-AMLP-1501",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Amalapuram",
      bus_numbers: ["654"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 160,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:15", "08:15", "12:30", "16:45"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-MTM-1601",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Machilipatnam",
      bus_numbers: ["432"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 150,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:00", "10:30", "14:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-RZL-1701",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Razole",
      bus_numbers: ["146"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 120,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:50",
          "07:35",
          "13:20",
          "14:45",
          "16:45",
          "17:55",
          "18:55",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GDV-1801",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Gudivada",
      bus_numbers: ["2K"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 90,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["04:55", "08:00", "11:00", "16:10", "19:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GNP-1901",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Ganapavaram",
      bus_numbers: ["460"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 45,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 04:25 to 20:30",
      },
    },
    {
      route_id: "BVRM-NDD-2001",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Nidadavolu",
      bus_numbers: ["111A"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 90,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:00",
          "06:30",
          "12:00",
          "13:45",
          "15:00",
          "15:45",
          "18:20",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-MGLT-2101",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Mogalthur",
      bus_numbers: ["333M"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 80,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:10", "09:40", "13:10", "17:20"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKDR-2201",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Vissakoderu",
      bus_numbers: ["305"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 35,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["08:00", "10:00", "12:00", "14:00", "16:00", "18:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VRVM-2301",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Veeravasaram",
      bus_numbers: ["306"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 40,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 1 hour from 07:00 to 19:00",
      },
    },
    {
      route_id: "BVRM-KLL-2401",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Kalla",
      bus_numbers: ["314", "314K"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 25,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 40 minutes from 06:45 to 20:05",
      },
    },
    {
      route_id: "BVRM-ATL-2501",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Attili",
      bus_numbers: ["268"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 65,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:45", "09:15", "13:30", "17:45"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-DDP-2601",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Doddiptla",
      bus_numbers: ["319"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 75,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["08:20", "12:50", "16:50"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-SSL-2701",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Seesali",
      bus_numbers: ["311S"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["09:05", "15:15", "18:10"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-KRKL-2801",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Korukollu",
      bus_numbers: ["313K"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:40", "11:20", "14:40", "17:50"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKP-302",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Visakhapatnam",
      bus_numbers: ["888V"],
      service_type: "Garuda (AC Volvo)",
      total_seats: 45,
      amenities: ["AC", "Recliner Seats", "Charging Ports", "Water Bottle"],
      estimated_duration_mins: 390,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["21:30", "22:30"],
        frequency_details: null,
      },
    },
  ],
};

const buses = {
  depot_name: "Bhimavaram APSRTC Depot",
  data_generated_on: "2025-09-16",
  bus_services: [
    {
      route_id: "BVRM-VJA-101",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Vijayawada",
      bus_numbers: ["111", "111H", "112"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 180,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 04:55 to 20:20",
      },
    },
    {
      route_id: "BVRM-VJA-102",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Vijayawada",
      bus_numbers: ["999A"],
      service_type: "Indra (AC)",
      total_seats: 40,
      amenities: ["AC", "Recliner Seats", "Charging Ports"],
      estimated_duration_mins: 160,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-HYD-201",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Hyderabad (MGBS)",
      bus_numbers: ["7745"],
      service_type: "Garuda (AC Volvo)",
      total_seats: 45,
      amenities: ["AC", "Recliner Seats", "Charging Ports", "Water Bottle"],
      estimated_duration_mins: 510,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["19:30", "20:30", "21:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-HYD-202",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Hyderabad (BHEL)",
      bus_numbers: ["7781"],
      service_type: "Super Luxury (Non-AC)",
      total_seats: 40,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 540,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["19:00", "20:00", "21:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKP-301",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Visakhapatnam",
      bus_numbers: ["444V"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 420,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:30", "08:30", "13:45", "21:00", "22:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-RJY-401",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Rajahmundry",
      bus_numbers: ["193", "233A"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 150,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 40 minutes from 04:50 to 19:35",
      },
    },
    {
      route_id: "BVRM-ELR-501",
      platform_number: 2,
      origin_depot: "Bhimavaram",
      destination: "Eluru",
      bus_numbers: ["7A"],
      service_type: "Express",
      total_seats: 55,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 100,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 05:35 to 21:15",
      },
    },
    {
      route_id: "BVRM-TPG-601",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tadepalligudem",
      bus_numbers: ["201T"],
      service_type: "Express",
      total_seats: 55,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 20 minutes from 05:00 to 21:00",
      },
    },
    {
      route_id: "BVRM-TNK-701",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tanuku",
      bus_numbers: ["252"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 25 minutes from 05:10 to 20:40",
      },
    },
    {
      route_id: "BVRM-NSP-801",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Narasapuram",
      bus_numbers: ["116"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 05:30 to 20:30",
      },
    },
    {
      route_id: "BVRM-PLK-901",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Palakollu",
      bus_numbers: ["158"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 45,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 25 minutes from 05:00 to 21:25",
      },
    },
    {
      route_id: "BVRM-AKVD-1001",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Akividu",
      bus_numbers: ["301"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 40,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 06:00 to 21:00",
      },
    },
    {
      route_id: "BVRM-KKLR-1101",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Kaikalur",
      bus_numbers: ["311"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 70,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:15",
          "07:45",
          "09:15",
          "11:30",
          "14:00",
          "16:30",
          "18:45",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-UNDI-1201",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Undi",
      bus_numbers: ["303"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 30,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 45 minutes from 06:30 to 20:00",
      },
    },
    {
      route_id: "BVRM-KKD-1301",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Kakinada",
      bus_numbers: ["555K"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 240,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:00", "07:15", "09:30", "11:45", "14:00", "16:15"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GNT-1401",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Guntur",
      bus_numbers: ["888G"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 210,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["06:45", "09:00", "11:15", "15:00", "17:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-AMLP-1501",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Amalapuram",
      bus_numbers: ["654"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 160,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:15", "08:15", "12:30", "16:45"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-MTM-1601",
      platform_number: 6,
      origin_depot: "Bhimavaram",
      destination: "Machilipatnam",
      bus_numbers: ["432"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 150,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:00", "10:30", "14:30"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-RZL-1701",
      platform_number: 3,
      origin_depot: "Bhimavaram",
      destination: "Razole",
      bus_numbers: ["146"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 120,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:50",
          "07:35",
          "13:20",
          "14:45",
          "16:45",
          "17:55",
          "18:55",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GDV-1801",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Gudivada",
      bus_numbers: ["2K"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 90,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["04:55", "08:00", "11:00", "16:10", "19:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-GNP-1901",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Ganapavaram",
      bus_numbers: ["460"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 45,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 30 minutes from 04:25 to 20:30",
      },
    },
    {
      route_id: "BVRM-NDD-2001",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Nidadavolu",
      bus_numbers: ["111A"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 90,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:00",
          "06:30",
          "12:00",
          "13:45",
          "15:00",
          "15:45",
          "18:20",
        ],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-MGLT-2101",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Mogalthur",
      bus_numbers: ["333M"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 80,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:10", "09:40", "13:10", "17:20"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKDR-2201",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Vissakoderu",
      bus_numbers: ["305"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 35,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["08:00", "10:00", "12:00", "14:00", "16:00", "18:00"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VRVM-2301",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Veeravasaram",
      bus_numbers: ["306"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 40,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 1 hour from 07:00 to 19:00",
      },
    },
    {
      route_id: "BVRM-KLL-2401",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Kalla",
      bus_numbers: ["314", "314K"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 25,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        departures: [],
        frequency_details: "Every 40 minutes from 06:45 to 20:05",
      },
    },
    {
      route_id: "BVRM-ATL-2501",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Attili",
      bus_numbers: ["268"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 65,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["05:45", "09:15", "13:30", "17:45"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-DDP-2601",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Doddiptla",
      bus_numbers: ["319"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 75,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["08:20", "12:50", "16:50"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-SSL-2701",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Seesali",
      bus_numbers: ["311S"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["09:05", "15:15", "18:10"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-KRKL-2801",
      platform_number: 7,
      origin_depot: "Bhimavaram",
      destination: "Korukollu",
      bus_numbers: ["313K"],
      service_type: "Palle Velugu",
      total_seats: 55,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["07:40", "11:20", "14:40", "17:50"],
        frequency_details: null,
      },
    },
    {
      route_id: "BVRM-VSKP-302",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Visakhapatnam",
      bus_numbers: ["888V"],
      service_type: "Garuda (AC Volvo)",
      total_seats: 45,
      amenities: ["AC", "Recliner Seats", "Charging Ports", "Water Bottle"],
      estimated_duration_mins: 390,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["21:30", "22:30"],
        frequency_details: null,
      },
    },
  ],
};

buses_three = {
  depot_name: "Bhimavaram APSRTC Depot",
  source_image_date: "2014-07-16",
  bus_services: [
    {
      route_id: "BVRM-GDV-2K",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Gudivada",
      bus_numbers: ["2K"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 90,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["04:55", "16:10"],
      },
    },
    {
      route_id: "BVRM-VJA-111",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Vijayawada",
      bus_numbers: ["111", "111H", "112", "54"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 180,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        frequency_details: "Every 20 minutes from 04:55 to 20:20",
      },
    },
    {
      route_id: "BVRM-ELR-145",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Eluru",
      bus_numbers: ["145"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 100,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "05:35",
          "06:05",
          "17:25",
          "18:10",
          "19:10",
          "20:30",
          "21:30",
        ],
      },
    },
    {
      route_id: "BVRM-BMD-291C",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Bhimadole",
      bus_numbers: ["291C"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 75,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:55",
          "11:30",
          "12:45",
          "15:00",
          "16:15",
          "19:55",
          "21:10",
        ],
      },
    },
    {
      route_id: "BVRM-TPG-201T",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tadepalligudem",
      bus_numbers: ["201T"],
      service_type: "Express",
      total_seats: 55,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        frequency_details: "Every 20 minutes from 05:00 to 21:00",
      },
    },
    {
      route_id: "BVRM-TNK-252",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Tanuku",
      bus_numbers: ["252"],
      service_type: "Ultra Deluxe",
      total_seats: 48,
      amenities: ["Non-AC", "Push-back Seats"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        frequency_details: "Every 25 minutes from 05:10 to 20:40",
      },
    },
    {
      route_id: "BVRM-NSP-116",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Narasapuram",
      bus_numbers: ["116"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 60,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: ["06:10", "16:40", "18:00"],
      },
    },
    {
      route_id: "BVRM-PLK-158",
      platform_number: 1,
      origin_depot: "Bhimavaram",
      destination: "Palakollu",
      bus_numbers: ["158"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 45,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        frequency_details: "Every 25 minutes from 05:00 to 21:25",
      },
    },
    {
      route_id: "BVRM-RJY-ALL",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Rajahmundry",
      bus_numbers: ["146", "233A", "3D", "193"],
      service_type: "Super Luxury",
      total_seats: 40,
      amenities: ["AC", "Push-back Seats"],
      estimated_duration_mins: 150,
      timings: {
        schedule_type: "HIGH_FREQUENCY",
        frequency_details: "Every 40 minutes from 04:50 to 19:35",
      },
    },
    {
      route_id: "BVRM-RZL-146",
      platform_number: 4,
      origin_depot: "Bhimavaram",
      destination: "Razole",
      bus_numbers: ["146"],
      service_type: "Express",
      total_seats: 52,
      amenities: ["Non-AC", "2+3 Seating"],
      estimated_duration_mins: 120,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:50",
          "07:35",
          "13:20",
          "14:45",
          "16:45",
          "17:55",
          "18:55",
        ],
      },
    },
    {
      route_id: "BVRM-MLP-50,55G",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Malleswaram",
      bus_numbers: ["50", "55G"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 70,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "05:15",
          "06:45",
          "08:52",
          "10:10",
          "12:50",
          "14:15",
          "16:15",
          "18:00",
          "19:00",
          "20:00",
        ],
      },
    },
    {
      route_id: "BVRM-PLK-77C",
      platform_number: 5,
      origin_depot: "Bhimavaram",
      destination: "Palakollu",
      bus_numbers: ["77C", "177"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:08",
          "06:45",
          "17:28",
          "18:00",
          "20:30",
          "21:05",
          "21:25",
          "21:55",
        ],
      },
    },
    {
      route_id: "BVRM-UNDI-3J",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Undi",
      bus_numbers: ["3J", "3D"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 30,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "05:07",
          "05:42",
          "06:15",
          "06:35",
          "07:05",
          "07:58",
          "11:12",
          "11:30",
          "14:17",
          "15:10",
          "17:47",
          "18:34",
          "19:18",
          "20:10",
          "20:33",
          "21:05",
        ],
      },
    },
    {
      route_id: "BVRM-AKVD-11J",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Akividu",
      bus_numbers: ["11J"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 40,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "04:01",
          "05:05",
          "05:43",
          "06:35",
          "07:10",
          "08:05",
          "08:31",
          "15:30",
          "16:55",
          "18:18",
          "19:05",
          "19:55",
        ],
      },
    },
    {
      route_id: "BVRM-KLL-31K",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Kalla",
      bus_numbers: ["31K", "31H"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 25,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "05:15",
          "05:55",
          "06:20",
          "06:50",
          "07:35",
          "09:37",
          "10:15",
          "12:10",
          "13:25",
          "15:00",
          "16:20",
          "17:40",
          "19:00",
          "19:35",
          "20:00",
        ],
      },
    },
    {
      route_id: "BVRM-PLK-26H",
      platform_number: 8,
      origin_depot: "Bhimavaram",
      destination: "Palakollu",
      bus_numbers: ["26H", "5"],
      service_type: "Palle Velugu",
      total_seats: 48,
      amenities: ["Non-AC", "3+2 Seating"],
      estimated_duration_mins: 50,
      timings: {
        schedule_type: "FIXED_DEPARTURE",
        departures: [
          "06:35",
          "07:07",
          "08:00",
          "09:30",
          "11:00",
          "11:35",
          "13:15",
          "14:00",
          "15:45",
          "16:35",
          "17:17",
          "18:15",
          "19:31",
        ],
      },
    },
  ],
};
